name: Run Pytest on push

on:
  [push]:
    branches: [main] # replace with the branch you want to run the tests on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10 # replace with the version of Python you want to use
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # replace with the name of your requirements file

    - name: Run Pytest - Linear Regression
      run: |
        pytest linear_regression/tests/
