name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests - LINEAR REGRESSION
      run: pytest 1_linear_regression/tests -vv

    - name: Run tests - K-NEAREST-NEIGHBORS
      run: pytest 2_knn_classification/tests/ -vv

    - name: Run tests - SUPPORT VECTOR MACHINES (svm)
      run: pytest 3_svm/tests/test_svm.py -vv

    - name: Run tests - K_MEANS
      run: pytest 4_k_means/tests/test_k_means.py -vv
